---
- hosts: sonic
  gather_facts: no
  become: true
  connection: httpapi 
  roles:
     - check-hosts-up
     - common
     - interfaces
     - vlans
     - vrfs
     - bgpunderlay 
     - vxlan-overlay
     - saveconf 

- hosts: clients  
  gather_facts: no
  become: true
  roles:
     - endhosts 
