---
# tasks file for saveconf
- name: "Save configuration"
  vars:
    ansible_connection: network_cli
  sonic_config:
    commands: ['write mem']
  register: result
  until: result is not failed
  retries: 100

- name: Reload config
  connection: ssh
  shell: config load -y
  register: result
