---
- name: "Config vxlan overlay"
  sonic_vxlans:
    config: "{{ sonic_vxlan_conf }}"
    state: merged
  when: sonic_vxlan_conf is defined and sonic_vxlan_conf
- name: "Config neigh suppress"
  vars:
    ansible_connection: network_cli
  sonic_config:
    lines: neigh-suppress
    parents: int Vlan{{ item.vlan_id }}
  register: result
  loop: "{{sonic_l2_vni_vlans_list}}"
  when: sonic_l2_vni_vlans_list is defined and sonic_l2_vni_vlans_list
- name: "Config anycast address"
  vars:
    ansible_connection: network_cli
  sonic_config:
    lines: ip anycast-address "{{item.prefix[:-4]+'254/24'}}"
    parents: int Vlan{{ item.vlan_id }}
  register: result
  loop: "{{sonic_vlans_prefix_list}}"
  when: item.prefix is defined and sonic_vlans_prefix_list is defined and sonic_vlans_prefix_list
- name: "Config anycast mac address"
  vars:
    ansible_connection: network_cli
  sonic_config:
    lines: ip anycast-mac-address "{{ sonic_anycast_mac_address }}"
  register: result
  when: sonic_anycast_mac_address is defined and sonic_anycast_mac_address
