---
- name: "Check switches up"
  hosts: sonic
  gather_facts: no
  connection: ssh
  become: true
  tasks:
  - name: wait for host up
    wait_for_connection:
      connect_timeout: 10 
      sleep: 5
      delay: 5
      timeout: 300
  - name: Check ping
    ansible.builtin.ping:
    register: output_ping
    until: output_ping.ping.find("pong") != -1
    retries: 100
  - debug:
      var: output_ping.ping
  - name: Check system readiness
    shell: show system status
    register: output_readiness
    until: output_readiness.stdout.find("System is ready") != -1
    retries: 100
  - debug:
      var: output_readiness.stdout
