---
- name: "SONiC Configure Switch"
  hosts: leafs
  gather_facts: no
  connection: httpapi
  become: true
  collections:
    - dellemc.sonic
  tasks:
  - name: Configures interfaces
    sonic_interfaces:
      config: "{{sonic_interfaces}}"
    when: sonic_interfaces is defined and sonic_interfaces
  - name: CREATE sonic_lag_interfaces merged state
    sonic_lag_interfaces:
      config: "{{sonic_lag_interfaces}}"
    when: sonic_lag_interfaces is defined and sonic_lag_interfaces
    tags:
      - test

