---
- name: "SONiC Configure BGP Overlay"
  hosts: sonic
  gather_facts: no
  connection: httpapi
  become: true
  collections:
    - dellemc.enterprise_sonic
  tasks:
  - name: Create BGP configuration
    sonic_bgp:
      config: "{{sonic_bgp}}"
    when: sonic_bgp is defined and sonic_bgp
  - name: Create BGP AF configuration
    sonic_bgp_af:
      config: "{{sonic_bgp_af}}"
    when: sonic_bgp_af is defined and sonic_bgp_af
  - name: Create BGP Neighbors configuration
    sonic_bgp_neighbors:
      config: "{{sonic_bgp_neighbors}}"
    when: sonic_bgp_neighbors is defined and sonic_bgp_neighbors
 - name: Create BGP Neighbors AF configuration
    sonic_bgp_neighbors_af:
      config: "{{sonic_bgp_neighbors_af}}"
    when: sonic_bgp_neighbors_af is defined and sonic_bgp_neighbors_af
