---
- name: "SONiC Configure L3 v2"
  hosts: leaf1
  gather_facts: no
  connection: httpapi
  become: true
  collections:
    - dellemc.enterprise_sonic
  tasks:
    - name: Configure L3
      sonic_l3_interfaces:
        config: "{{sonic_l3_interfaces}}"
      when: sonic_l3_interfaces is defined and sonic_l3_interfaces
