---
- name: "SONiC Configure L3 v2"
  hosts: leafs
  gather_facts: no
  connection: httpapi
  become: true
  collections:
    - dellemc.enterprise_sonic
  tasks:
    - name: Configure L3
      sonic_l3_interfaces:
        config: 
          - name: Vlan4094
        state: deleted
