---
- name: "SONiC Configure Switch"
  hosts: sonic
  gather_facts: no
  connection: httpapi
  become: true
  collections:
    - dellemc.sonic
  tasks:
    - name: Perform PUT operation to disable ztp
      sonic_api:
        url: data/openconfig-ztp:ztp/config/admin-mode 
        method: "PATCH"
        body: {"openconfig-ztp:admin-mode":true}   
        status_code: 201
    - name: Perform PATCH operation to set hostanme
      sonic_api:
        url: data/openconfig-system:system/config/hostname
        method: "PUT"
        body: { "openconfig-system:hostname": "{{inventory_hostname}}"}
        status_code: 204
    - name: Perform PUT operation to set routing mode split
      sonic_api:
        url: data/sonic-device-metadata:sonic-device-metadata/DEVICE_METADATA/DEVICE_METADATA_LIST=localhost/docker_routing_config_mode
        method: "PUT"
        body: {"sonic-device-metadata:docker_routing_config_mode":"split"}
        status_code: 204
    - name: Perform PUT operation to enable mgmt vrf
      sonic_api:
        url: data/sonic-mgmt-vrf:sonic-mgmt-vrf
        method: "PUT"
        body: {"sonic-mgmt-vrf:sonic-mgmt-vrf":{"MGMT_VRF_CONFIG":{"MGMT_VRF_CONFIG_LIST":[{"vrf_global_name":"vrf_global","mgmtVrfEnabled":true,"in_band_mgmt_enabled":true}]}}}
        status_code: 204
    - name: Perform PUT operation to configure loopbacks 
      sonic_api:
        url: data/sonic-loopback:sonic-loopback
        method: "PUT"
        body: {"sonic-loopback:sonic-loopback":{"LOOPBACK":{"LOOPBACK_LIST":[{"name":"Loopback0","description":"Loopback Underlay"},{"name":"Loopback1","description":"Loopback MLAG"}]}}}
        status_code: 201
    - name: Host Count
      debug:
        msg: "{{ groups['leafs'] | length }}"
      tags:
         - test
