---
- name: "Save config"
  hosts: sonic
  gather_facts: no
  connection: network_cli
  become: true
  collections:
    - dellemc.enterprise_sonic
  tasks:
  - name: "Save configuration"
    vars:
      ansible_connection: network_cli
    sonic_config:
      commands: ['write mem']
    register: result
