---
# tasks file for check-hosts-up
- name: wait for host up
  wait_for_connection:
    connect_timeout: 10
    sleep: 5
    delay: 5
    timeout: 300

- name: Check ping
  ansible.builtin.ping:
  register: output_ping
  until: output_ping.ping.find("pong") != -1
  retries: 100

- name: Check system readiness
  connection: ssh
  shell: show system status
  register: output_readiness
  until: output_readiness.stdout.find("System is ready") != -1
  retries: 100
 
- name: Pause before next action
  pause: seconds=5 
